### ISSUE TITLE
False positive on implementing interface

### ISSUE THREAD

**Issue by robinknaapen** [mvdan/unparam#52]
```yml
// .golangci.yml
linters:
  disable-all: true
  enable:
    - unparam
```

```Go
// lower implements encoding.TextUnmarshaler to force lowercase
type lower string

// unparam: (*lower).UnmarshalText - result 0 (error) is always nil
func (l *lower) UnmarshalText(b []byte) error {
    s := strings.ToLower(string(b))

    *l = lower(s)
    return nil
}
```
